version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./build/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./build/certs/key.pem:/etc/ssl/certs/key.pem
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    depends_on:
      - frontend
      - backend
  frontend:
    build:
        context: .
        dockerfile: DockerfileFrontend
        args:
          - BASE_URL=http://localhost
    container_name: frontend
    command: "npm run start"
    ports:
      - 8081:8081
    expose:
    - 8081
    environment:
      - HOST=0.0.0.0
      - PORT=8081
    networks:
    - default
  backend:
      build:
        context: .
        dockerfile: DockerfileBackend
      container_name: backend
      command: bash -c "gunicorn choban.wsgi:application --bind 0.0.0.0:8080"
      ports:
        - 8080:8080
      expose:
        - 8080
      volumes:
        - media_volume:/usr/src/app/media
        - static_volume:/usr/src/app/static
        - ./build/.env:/backend/.env
      environment:
        - STATICFILES_DIR=/usr/src/app/static
        - MEDIAFILES_DIR=/usr/src/app/media
      networks:
        - default
  db:
      image: postgres:11.1-alpine
      restart: always
      container_name: db
      environment:
        POSTGRES_PASSWORD: "!9ty9I6oiU@9*b"
        POSTGRES_DB: choban
        POSTGRES_USER: choban
      networks:
        - default
      volumes:
        - backup_volume:/docker-entrypoint-initdb.d/latest.dump
volumes:
  media_volume:
  static_volume:
  backup_volume: