version: '3'

services:
  nginx:
    build: .
    container_name: nginx
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
  api:
      build:
        context: .
        dockerfile: DockerfileBackend
      container_name: api
      command: bash -c "python manage.py collectstatic --no-input && gunicorn choban.wsgi:application --bind 0.0.0.0:8080"
      ports:
        - 8080:8080
      expose:
        - 8080
      volumes:
        - media_volume:/usr/src/app/media
        - static_volume:/usr/src/app/static
        - ./build/.env:/backend/.env
      environment:
        - STATICFILES_DIR=/usr/src/app/static
        - MEDIAFILES_DIR=/usr/src/app/media

volumes:
  media_volume:
  static_volume: