version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./build/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./build/certs/key.pem:/etc/ssl/certs/key.pem
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
      - 443:443
  frontend:
    build:
        context: .
        dockerfile: DockerfileFrontend
    container_name: frontend
    command: "npm run start"
    ports:
      - 8081:8081
    depends_on:
      - nginx
    expose:
    - 8081
    environment:
      - HOST=0.0.0.0
      - PORT=8081
  backend:
      build:
        context: .
        dockerfile: DockerfileBackend
      container_name: backend
      command: bash -c "python manage.py collectstatic --no-input && gunicorn choban.wsgi:application --bind 0.0.0.0:8080"
      ports:
        - 8080:8080
      expose:
        - 8080
      volumes:
        - media_volume:/usr/src/app/media
        - static_volume:/usr/src/app/static
        - ./build/.env:/backend/.env
      environment:
        - STATICFILES_DIR=/usr/src/app/static
        - MEDIAFILES_DIR=/usr/src/app/media

volumes:
  media_volume:
  static_volume:
